# Generated by Django 3.2.16 on 2022-11-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_unique_user_subscribers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_subscribers',
        ),
    ]
